language: scala

env:
  - PARADOX_LANGUAGE=java
  - PARADOX_LANGUAGE=scala

script: sbt test paradox

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: target/paradox/site/main
  on:
    branch: master
    condition: $PARADOX_LANGUAGE = scala
